dist: trusty
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_script:
  - npm install -g coveralls
script:
   - npm install
   - npm test
notifications:
  irc: "irc.freenode.org#brass-monkey"
branches:
  only:
    - master
after_success:
  - rpm run coverage
  - cat ./coverage/lcov.info | coveralls